<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/06/01 02:15:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=Jobeetejemplo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
